version: '3'

volumes:
  localstack_tmp: { }

services:
  localstack:
    build:
      context: ./compose/localstack
      dockerfile: Dockerfile
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,sns
      - HOSTNAME_EXTERNAL=localstack
      - DEFAULT_REGION=eu-west-1
    volumes:
      - "localstack_tmp:/tmp/localstack"
