name: Build and push pdf-to-alto docker image

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        id: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: docker-setup-buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/dlcs/pdf-to-alto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,enable=true,prefix=,format=long
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Login to GitHub Container Registry
        id: docker-login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker-build-push
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.docker-setup-buildx.outputs.name }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          push: true
